module.exports = {
  add: require('./src/add'),
  and: require('./src/and'),
  compose: require('./src/compose'),
  curry: require('./src/curry'),
  gt: require('./src/gt'),
  gte: require('./src/gte'),
  head: require('./src/head'),
  lt: require('./src/lt'),
  lte: require('./src/lte'),
  or: require('./src/or'),
  pipe: require('./src/pipe'),
  slice: require('./src/slice'),
  tail: require('./src/tail'),
}
